tap 'caskroom/cask'

brew 'git'
brew 'npm'
brew 'zsh'
brew 'zsh-completions'
brew 'yarn'

cask 'flux'
cask 'firefox'
cask 'firefoxdeveloperedition'
cask 'gimp'
cask 'transmit'
cask 'google-chrome'
cask 'hyper'
cask 'sublime-text'
cask 'mamp'
cask 'sequel-pro'
cask 'vlc'
cask 'spotify'
cask 'imageoptim'

mas 'Slack', id: 803453959
mas 'Magnet', id: 441258766
mas 'App Cleaner & Uninstaller', id: 1013897218